# Generated by Django 4.2.7 on 2025-09-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('estimated_drive_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_trip_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('driver_name', models.CharField(default='John Doe', max_length=255)),
                ('carrier_name', models.CharField(default='DHL Carrier', max_length=255)),
                ('vehicle_number', models.CharField(default='TRK-1234', max_length=50)),
                ('total_miles', models.IntegerField()),
                ('off_duty', models.JSONField(default=list)),
                ('sleeper_berth', models.JSONField(default=list)),
                ('driving', models.JSONField(default=list)),
                ('on_duty', models.JSONField(default=list)),
                ('remarks', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
        ),
    ]
