# Generated by Django 4.2.7 on 2025-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlog',
            name='driver_name',
            field=models.CharField(default='Felix Savali', max_length=255),
        ),
    ]
